name: petroflow
description: "The PetroFlow Mobile Application."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  animated_text_kit: ^4.2.3
  http: ^1.3.0
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  syncfusion_flutter_charts: ^28.2.9
  dio: ^5.8.0+1
  drift: ^2.25.1
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.31
  connectivity_plus: ^6.1.3
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main
  local_auth: ^2.3.0
  firebase_messaging: ^15.2.4
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.17
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  fluttertoast: ^8.2.12
  firebase_core: ^3.12.1
  intl: ^0.18.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_svg: ^2.0.17
  drift_dev: ^2.25.2
  build_runner: ^2.4.15

flutter:

  uses-material-design: true

  assets:
    - images/logo.png
    - images/logo.svg
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf